# Generated by Django 6.0.3 on 2026-04-10 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('major', models.CharField(max_length=100, unique=True, verbose_name='전공 카테고리')),
            ],
            options={
                'verbose_name': '전공',
                'verbose_name_plural': '전공',
                'db_table': 'major',
                'ordering': ['major'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('post_type', models.CharField(choices=[('TIP', '꿀팁'), ('MAJOR', '전공')], max_length=10, verbose_name='게시글 유형')),
                ('category', models.CharField(blank=True, choices=[('PLACE', '장소'), ('DORM_LIFE', '기숙사생활'), ('SCHOOL_LIFE', '대마고생활'), ('ETC', '기타')], help_text='TIP: 장소/기숙사생활/대마고생활/기타, MAJOR: MajorTag로 관리', max_length=20, verbose_name='카테고리')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('place', models.ForeignKey(blank=True, help_text='TIP 전용, nullable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='places.place', verbose_name='태그된 장소')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MajorTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_tags', to='posts.major', verbose_name='대상 전공')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_tags', to='posts.post', verbose_name='대상 게시글')),
            ],
            options={
                'verbose_name': '전공 태그',
                'verbose_name_plural': '전공 태그',
                'db_table': 'major_tag',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='좋아요 생성일')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사용자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post', verbose_name='좋아요 대상 게시글')),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요',
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent', models.ForeignKey(blank=True, help_text='대댓글일 경우 작성', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment', verbose_name='부모 댓글')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='대상 게시글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAnonymousUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_number', models.IntegerField(help_text='1부터 증가', verbose_name='게시글 내 익명 순번')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_users', to='posts.post', verbose_name='게시글')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_mappings', to=settings.AUTH_USER_MODEL, verbose_name='실제 사용자')),
            ],
            options={
                'verbose_name': '게시글 익명 사용자',
                'verbose_name_plural': '게시글 익명 사용자',
                'db_table': 'post_anonymous_user',
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500, verbose_name='이미지 URL')),
                ('order_index', models.IntegerField(help_text='0부터 시작하는 순서', verbose_name='이미지 표시 순서')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post', verbose_name='연결된 게시글')),
            ],
            options={
                'verbose_name': '게시글 이미지',
                'verbose_name_plural': '게시글 이미지',
                'db_table': 'post_image',
                'ordering': ['post', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-created_at'], name='post_post_ty_3bd8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category'], name='post_categor_e3adb5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_created_f85ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='majortag',
            index=models.Index(fields=['post'], name='major_tag_post_id_6751f7_idx'),
        ),
        migrations.AddIndex(
            model_name='majortag',
            index=models.Index(fields=['major'], name='major_tag_major_i_835747_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='majortag',
            unique_together={('post', 'major')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post'], name='like_post_id_b42a77_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='like_user_id_8ed00c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='comment_post_id_ca4368_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comment_parent__834718_idx'),
        ),
        migrations.AddIndex(
            model_name='postanonymoususer',
            index=models.Index(fields=['post', 'user'], name='post_anonym_post_id_2ec6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'order_index'], name='post_image_post_id_85e754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postimage',
            unique_together={('post', 'order_index')},
        ),
    ]
