# Generated by Django 6.0.3 on 2026-04-10 02:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='장소명')),
                ('description', models.TextField(verbose_name='설명')),
                ('category', models.CharField(choices=[('RESTAURANT', '맛집'), ('CAFE', '카페'), ('PC_ROOM', 'PC방'), ('KARAOKE', '노래방'), ('ETC', '기타')], max_length=20, verbose_name='카테고리')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('naver_map_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='네이버지도 링크')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='익명 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '장소',
                'verbose_name_plural': '장소',
                'db_table': 'place',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='place_categor_4ba94d_idx'), models.Index(fields=['-created_at'], name='place_created_e5dfda_idx')],
            },
        ),
    ]
