# Generated by Django 6.0.3 on 2026-04-10 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(help_text='학년-반-번호 형식 (예: 1-2-3)', max_length=20, unique=True, verbose_name='학번')),
                ('grade', models.IntegerField(help_text='학년 (1~3)', verbose_name='학년')),
                ('class_num', models.IntegerField(help_text='반 번호', verbose_name='반')),
                ('num', models.IntegerField(help_text='번호', verbose_name='번호')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('cohort', models.IntegerField(help_text='대마고 기수', verbose_name='기수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'user',
                'indexes': [models.Index(fields=['cohort'], name='user_cohort_5ed59b_idx')],
                'unique_together': {('grade', 'class_num', 'num')},
            },
        ),
    ]
