# Generated by Django 6.0.3 on 2026-04-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='DSM 계정 ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cohort',
            field=models.IntegerField(blank=True, help_text='대마고 기수', null=True, verbose_name='기수'),
        ),
    ]
