# Generated by Django 6.0.3 on 2026-04-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_id_alter_user_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='', max_length=255, verbose_name='비밀번호 해시'),
        ),
    ]
